name: Automated Tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default: second_test
        type: choice
        options:
          - first_test
          - second_test

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # эта джоба нужна для того, чтобы предыдущие результаты копировались в allure-results
  download-history:
    runs-on: ubuntu-latest
    name: Download history
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      #Скачиваем последни артифакт allure-results
      - name: Download latest allure-results artifact
        run: |
          ARTIFACT_ID=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PERSONAL_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/marinabulantsova/CIProject/actions/artifacts?name=allure-results |
            python -c "import sys, json; print(json.load(sys.stdin)['artifacts'][0]['id'])")

          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PERSONAL_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/marinabulantsova/CIProject/actions/artifacts/$ARTIFACT_ID/zip \
            -o artifacts.zip
          
          PEPORT_ID=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PERSONAL_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/marinabulantsova/CIProject/actions/artifacts?name=github-pages |
            python -c "import sys, json; print(json.load(sys.stdin)['artifacts'][0]['id'])")

          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PERSONAL_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/marinabulantsova/CIProject/actions/artifacts/$PEPORT_ID/zip \
            -o pages.zip

      - name: Unzip allure-results
        run: mkdir allure-results && unzip artifacts.zip -d allure-results

      - name: Unzip allure-results
        run: mkdir old-pages pages_history && unzip pages.zip -d old-pages && tar -xvf old-pages/artifact.tar -C pages_history

      - name: Copy from pages_history to allure-results
        run: cp pages_history/history/* allure-results && cp pages_history/history allure-results

      - name: Store allure history
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
          retention-days: 1

  test:
    runs-on: ubuntu-latest
    needs: download-history
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4

      - name: first_test
        if: github.event.inputs.deployment_target == 'first_test'
        run: pytest tests/test_button.py::test_button_exist --alluredir=allure-results

      - name: second_test
        if: github.event.inputs.deployment_target == 'second_test'
        run: pytest tests/test_button.py::test_button_exist_2 --alluredir=allure-results

      - name: Store allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
          retention-days: 1

  generate-report:
    runs-on: ubuntu-latest
    needs: test
    name: Generate report
    steps:
      - name: Java install
        uses: actions/setup-java@v5
        with:
          distribution: 'microsoft'
          java-version: '17'

      - name: Allure install
        run: |
          sudo wget https://github.com/allure-framework/allure2/releases/download/2.35.1/allure-2.35.1.tgz && \
          sudo tar -zxvf allure-2.35.1.tgz -C /opt/ && \
          sudo ln -s /opt/allure-2.35.1/bin/allure /usr/bin/allure

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4

      - name: Allure generate
        run: allure generate -c allure-results -o _site

      - name: Store allure report
        uses: actions/upload-artifact@v4
        with:
          name: _site
          path: _site
          retention-days: 1

  publish-report:
    runs-on: ubuntu-latest
    needs: generate-report
    name: Report publication
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3

      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4